// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // .env is gitignored, so fall back to the local dev file. This keeps a fresh
    // clone (and CI, which only needs `prisma generate`) working without setup.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
